global using System.Collections.Immutable;
global using System.Reflection;
global using Grpc.Core;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Abstractions;
global using Microsoft.AspNetCore.Mvc.Controllers;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.OpenApi.Models;
global using MongoDB.Driver;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using static HateoasExtensions;
