services:
  catalog-api:
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    ports:
      - 5000:80
    environment:
      - Database=server=catalog-db;uid=root;pwd=root;database=catalog;IgnoreCommandTransaction=true
      - Kafka=kafka
      - IdentityServiceUrl=http://identity-service
  carting-api:
    build:
      context: .
      dockerfile: CartingService/Dockerfile
    ports:
      - 5001:5001
      - 5003:5003
    environment:
      - DatabaseConnection=mongodb://carting-db:27017
      - DatabaseName=carting
      - KafkaServer=kafka
      - KafkaGroup=carting-kafka-group
      - IdentityServiceUrl=http://identity-service
  identity-service:
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    ports:
      - 5002:80
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - 5100:80
  catalog-db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ALLOW_PLAINTEXT_LISTENER=yes
  carting-db:
    image: mongo
    ports:
      - 27017:27017
