global using System.Collections.Immutable;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq.Expressions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.OpenApi.Models;
global using MySqlConnector;
global using static HateoasExtensions;
global using GraphQL;
global using GraphQL.DataLoader;
global using GraphQL.SystemTextJson;
global using GraphQL.Types;
