name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - curl http://178.74.224.103:4999/redeploy -H "token: ${{ secrets.deploytoken }}"
